export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
export const GET_VIDEOGAMES_BY_NAME = "GET_VIDEOGAME_BY_NAME";
export const GET_GENRES = "GET_GENRES";
export const POST_VIDEOGAME = "POST_VIDEOGAME";
export const GET_AGAIN = "GET_AGAIN";
export const ORDER_CARDS = "ORDER_CARDS";
export const FILTER_CARDS = "FILTER_CARDS";
export const DELETE_ALL = "DELETE_ALL";
